-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "16")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        blur = {
            enabled = true,
            passes = 2,
            size = 10,
            vibrancy = 0.2,
        },
        inactive_opacity = 0.9,
        rounding = 12,
    },
    general = {
        border_size = 1,
        gaps_out = 6,
        layout = "scrolling",
    },
    input = {
        kb_layout = "br",
        sensitivity = -0.1,
    },
    scrolling = {
        focus_fit_method = 1,
    },
})

-- Keybinds
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.unbind("SUPER + C")
hl.bind("SUPER + X", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
